version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 761127wk
      MYSQL_DATABASE: ad
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    build: ./SecondHand
    container_name: springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ad
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 761127wk
    depends_on:
      - mysql
    ports:
      - "8080:7079"

  vue:
    build: ./frontend-vue
    container_name: vue
    environment:
      VITE_API_URL: "http://springboot:8080"
    ports:
      - "80:80"

volumes:
  mysql_data:
