spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/web/
    cache: false
    suffix: .html
aliyun:
  oss:
    bucket-name: project2-bucket
    endpoint: oss-ap-southeast-1.aliyuncs.com
    access-key-id: 123
    access-key-secret: 123
    file-host: secondHand