-- schema.sql
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_SECURITY_QUESTIONS;

CREATE TABLE USERS (
                       id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       username VARCHAR(50) UNIQUE,
                       password VARCHAR(100),
                       email VARCHAR(100),
                       name VARCHAR(100),
                       phone VARCHAR(15),
                       address1 VARCHAR(255),
                       address2 VARCHAR(255),
                       avatar VARCHAR(255),
                       role VARCHAR(50)
);

CREATE TABLE USER_SECURITY_QUESTIONS (
                                         id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                         username VARCHAR(50),
                                         question VARCHAR(255),
                                         answer VARCHAR(255),
                                         FOREIGN KEY (username) REFERENCES USERS(username)
);
