name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

#    - name: Build with Maven
#      run: mvn clean install --no-progress --batch-mode

#    - name: Run unit tests
#      run: mvn test
#
#    - name: Lint code
#      run: mvn checkstyle:check
#
#    - name: Upload test results
#      if: always()
#      uses: actions/upload-artifact@v3
#      with:
#        name: test-results
#        path: target/surefire-reports/






