name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - master
      - cicd
  pull_request:
    branches:
      - master
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('SecondHand/SecondHand/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      working-directory: SecondHand/SecondHand/
      run: mvn clean install -B

#    - name: Run JUnit Tests
#      working-directory: SecondHand
#      run: mvn test

#    - name: Set up Node.js
#      uses: actions/setup-node@v2
#      with:
#        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run integration tests
      run: npm run test:integration





