name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - master
      - cicd
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

