name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 200158
          MYSQL_DATABASE: ad
          MYSQL_USER: root
          MYSQL_PASSWORD: 200158
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ad?useSSL=false&serverTimezone=Asia/Singapore&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 200158

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('SecondHand/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      working-directory: SecondHand
      run: mvn clean install -B

#    - name: Run JUnit Tests
#      working-directory: SecondHand
#      run: mvn test

#    - name: Set up Node.js
#      uses: actions/setup-node@v2
#      with:
#        node-version: '20'

#    - name: Install dependencies
#      run: npm install
#
#    - name: Run integration tests
#      run: npm run test:integration





