name: Frontend Vue Tests

on:
  push:
    branches:
      - main
      - cicd
      - release
  pull_request:
    branches:
      - main
      - cicd
      - release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend-vue
        run: npm install

      - name: Run unit tests
        working-directory: frontend-vue
        run: npm run test
